INSERT INTO
    core_currency (country, code, symbol)
VALUES
    ('Afghanistan', 'AFN', '؋'),
    ('Albania', 'ALL', 'L'),
    ('Algeria', 'DZD', 'د.ج'),
    ('Andorra', 'EUR', '€'),
    ('Angola', 'AOA', 'Kz'),
    ('Antigua and Barbuda', 'XCD', '$'),
    ('Argentina', 'ARS', '$'),
    ('Armenia', 'AMD', '֏'),
    ('Australia', 'AUD', '$'),
    ('Austria', 'EUR', '€'),
    ('Azerbaijan', 'AZN', '₼'),
    ('Bahamas', 'BSD', '$'),
    ('Bahrain', 'BHD', '.د.ب'),
    ('Bangladesh', 'BDT', '৳'),
    ('Barbados', 'BBD', '$'),
    ('Belarus', 'BYR', 'Br'),
    ('Belgium', 'EUR', '€'),
    ('Belize', 'BZD', 'BZ$'),
    ('Benin', 'XOF', 'CFA'),
    ('Bhutan', 'BTN', 'Nu.'),
    ('Bolivia', 'BOB', '$b'),
    ('Bosnia and Herzegovina', 'BAM', 'KM'),
    ('Botswana', 'BWP', 'P'),
    ('Brazil', 'BRL', 'R$'),
    ('Brunei', 'BND', '$'),
    ('Bulgaria', 'BGN', 'лв'),
    ('Burkina Faso', 'XOF', 'CFA'),
    ('Burundi', 'BIF', 'FBu'),
    ('Cabo Verde', 'CVE', '$'),
    ('Cambodia', 'KHR', '៛'),
    ('Cameroon', 'XAF', 'CFA'),
    ('Canada', 'CAD', '$'),
    ('Central African Republic', 'XAF', 'CFA'),
    ('Chad', 'XAF', 'CFA'),
    ('Chile', 'CLP', '$'),
    ('China', 'CNY', '¥'),
    ('Colombia', 'COP', '$'),
    ('Comoros', 'KMF', 'C'),
    ('Congo (Brazzaville)', 'XAF', 'CFA'),
    ('Congo (Kinshasa)', 'CDF', 'FC'),
    ('Costa Rica', 'CRC', '₡'),
    ('Cote d\'Ivoire', 'XOF', 'CFA'),
    ('Croatia', 'HRK', 'kn'),
    ('Cuba', 'CUP', '$'),
    ('Cyprus', 'EUR', '€'),
    ('Czech Republic', 'CZK', 'Kč'),
    ('Denmark', 'DKK', 'kr'),
    ('Djibouti', 'DJF', 'Fr'),
    ('Dominica', 'XCD', '$'),
    ('Dominican Republic', 'DOP', '$'),
    ('Ecuador', 'USD', '$'),
    ('Egypt', 'EGP', '£'),
    ('El Salvador', 'USD', '$'),
    ('Equatorial Guinea', 'XAF', 'CFA'),
    ('Eritrea', 'ERN', 'Nkf'),
    ('Estonia', 'EUR', '€'),
    ('Eswatini', 'SZL', 'L'),
    ('Ethiopia', 'ETB', 'Br'),
    ('Fiji', 'FJD', '$'),
    ('Finland', 'EUR', '€'),
    ('France', 'EUR', '€'),
    ('Gabon', 'XAF', 'CFA'),
    ('Gambia', 'GMD', 'D'),
    ('Georgia', 'GEL', '₾'),
    ('Germany', 'EUR', '€'),
    ('Ghana', 'GHS', '₵'),
    ('Greece', 'EUR', '€'),
    ('Grenada', 'XCD', '$'),
    ('Guatemala', 'GTQ', 'Q'),
    ('Guinea', 'GNF', 'Fr'),
    ('Guinea-Bissau', 'XOF', 'CFA'),
    ('Guyana', 'GYD', '$'),
    ('Haiti', 'HTG', 'G'),
    ('Honduras', 'HNL', 'L'),
    ('Hungary', 'HUF', 'Ft'),
    ('Iceland', 'ISK', 'kr'),
    ('India', 'INR', '₹'),
    ('Indonesia', 'IDR', 'Rp'),
    ('Iran', 'IRR', '﷼'),
    ('Iraq', 'IQD', 'ع.د'),
    ('Ireland', 'EUR', '€'),
    ('Israel', 'ILS', '₪'),
    ('Italy', 'EUR', '€'),
    ('Jamaica', 'JMD', '$'),
    ('Japan', 'JPY', '¥'),
    ('Jordan', 'JOD', 'د.ا'),
    ('Kazakhstan', 'KZT', '₸'),
    ('Kenya', 'KES', 'KSh'),
    ('Kiribati', 'AUD', '$'),
    ('Korea, North', 'KPW', '₩'),
    ('Korea, South', 'KRW', '₩'),
    ('Kosovo', 'EUR', '€'),
    ('Kuwait', 'KWD', 'د.ك'),
    ('Kyrgyzstan', 'KGS', 'лв'),
    ('Laos', 'LAK', '₭'),
    ('Latvia', 'EUR', '€'),
    ('Lebanon', 'LBP', 'ل.ل'),
    ('Lesotho', 'LSL', 'L'),
    ('Liberia', 'LRD', '$'),
    ('Libya', 'LYD', 'ل.د'),
    ('Liechtenstein', 'CHF', 'Fr.'),
    ('Lithuania', 'EUR', '€'),
    ('Luxembourg', 'EUR', '€'),
    ('Madagascar', 'MGA', 'Ar'),
    ('Malawi', 'MWK', 'MK'),
    ('Malaysia', 'MYR', 'RM'),
    ('Maldives', 'MVR', 'ރ'),
    ('Mali', 'XOF', 'CFA'),
    ('Malta', 'EUR', '€'),
    ('Marshall Islands', 'USD', '$'),
    ('Mauritania', 'MRU', 'UM'),
    ('Mauritius', 'MUR', '₨'),
    ('Mexico', 'MXN', '$'),
    ('Micronesia', 'USD', '$'),
    ('Moldova', 'MDL', 'L'),
    ('Monaco', 'EUR', '€'),
    ('Mongolia', 'MNT', '₮'),
    ('Montenegro', 'EUR', '€'),
    ('Morocco', 'MAD', 'د.م.'),
    ('Mozambique', 'MZN', 'MT'),
    ('Myanmar (Burma)', 'MMK', 'Ks'),
    ('Namibia', 'NAD', '$'),
    ('Nauru', 'AUD', '$'),
    ('Nepal', 'NPR', '₨'),
    ('Netherlands', 'EUR', '€'),
    ('New Zealand', 'NZD', '$'),
    ('Nicaragua', 'NIO', 'C$'),
    ('Niger', 'XOF', 'CFA'),
    ('Nigeria', 'NGN', '₦'),
    ('North Macedonia', 'MKD', 'ден'),
    ('Norway', 'NOK', 'kr'),
    ('Oman', 'OMR', 'ر.ع.'),
    ('Pakistan', 'PKR', '₨'),
    ('Palau', 'USD', '$'),
    ('Panama', 'PAB', 'B/.'),
    ('Papua New Guinea', 'PGK', 'K'),
    ('Paraguay', 'PYG', 'Gs'),
    ('Peru', 'PEN', 'S/.'),
    ('Philippines', 'PHP', '₱'),
    ('Poland', 'PLN', 'zł'),
    ('Portugal', 'EUR', '€'),
    ('Qatar', 'QAR', 'ر.ق'),
    ('Romania', 'RON', 'lei'),
    ('Russia', 'RUB', '₽'),
    ('Rwanda', 'RWF', 'FRw'),
    ('Saint Kitts and Nevis', 'XCD', '$'),
    ('Saint Lucia', 'XCD', '$'),
    ('Saint Vincent and the Grenadines', 'XCD', '$'),
    ('Samoa', 'WST', 'T'),
    ('San Marino', 'EUR', '€'),
    ('Sao Tome and Principe', 'STN', 'Db'),
    ('Saudi Arabia', 'SAR', 'ر.س'),
    ('Senegal', 'XOF', 'CFA'),
    ('Serbia', 'RSD', 'дин.'),
    ('Seychelles', 'SCR', '₨'),
    ('Sierra Leone', 'SLL', 'Le'),
    ('Singapore', 'SGD', '$'),
    ('Slovakia', 'EUR', '€'),
    ('Slovenia', 'EUR', '€'),
    ('Solomon Islands', 'SBD', '$'),
    ('Somalia', 'SOS', 'S'),
    ('South Africa', 'ZAR', 'R'),
    ('South Sudan', 'SSP', '£'),
    ('Spain', 'EUR', '€'),
    ('Sri Lanka', 'LKR', '₨'),
    ('Sudan', 'SDG', '£'),
    ('Suriname', 'SRD', '$'),
    ('Sweden', 'SEK', 'kr'),
    ('Switzerland', 'CHF', 'Fr.'),
    ('Syria', 'SYP', '£'),
    ('Taiwan', 'TWD', 'NT$'),
    ('Tajikistan', 'TJS', 'ЅМ'),
    ('Tanzania', 'TZS', 'TSh'),
    ('Thailand', 'THB', '฿'),
    ('Timor-Leste', 'USD', '$'),
    ('Togo', 'XOF', 'CFA'),
    ('Tonga', 'TOP', 'T$'),
    ('Trinidad and Tobago', 'TTD', '$'),
    ('Tunisia', 'TND', 'د.ت'),
    ('Turkey', 'TRY', '₺'),
    ('Turkmenistan', 'TMT', 'm'),
    ('Tuvalu', 'AUD', '$'),
    ('Uganda', 'UGX', 'USh'),
    ('Ukraine', 'UAH', '₴'),
    ('United Arab Emirates', 'AED', 'د.إ'),
    ('United Kingdom', 'GBP', '£'),
    ('United States', 'USD', '$'),
    ('Uruguay', 'UYU', '$U'),
    ('Uzbekistan', 'UZS', 'лв'),
    ('Vanuatu', 'VUV', 'VT'),
    ('Vatican City', 'EUR', '€'),
    ('Venezuela', 'VES', 'Bs.'),
    ('Vietnam', 'VND', '₫'),
    ('Yemen', 'YER', '﷼'),
    ('Zambia', 'ZMW', 'ZK'),
    ('Zimbabwe', 'ZWL', '$');