version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: example-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootx
    volumes:
      - example-mysql-data:/var/lib/mysql
    ports:
      - "3306:3304"

volumes:
  example-mysql-data:
