INSERT INTO
    expenses_usagetag (title, code)
VALUES
    ('Advertising', 'ADV'),
    ('Charity', 'CHT'),
    ('Donations', 'DNT'),
    ('Education', 'EDU'),
    ('Food and Dining', 'FND'),
    ('Groceries', 'GRC'),
    ('Healthcare', 'HLT'),
    ('Insurance', 'INS'),
    ('Leisure and Entertainment', 'LEI'),
    ('Mortgage', 'MRT'),
    ('Rent', 'REN'),
    ('Shopping', 'SHP'),
    ('Transportation', 'TRP'),
    ('Utilities', 'UTL'),
    ('Travel', 'TRV'),
    ('Investments', 'INV'),
    ('Savings', 'SAV'),
    ('Loans', 'LOA'),
    ('Taxes', 'TAX'),
    ('Business Expenses', 'BEX'),
    ('Home Improvement', 'HIM'),
    ('Childcare', 'CHC'),
    ('Debt Repayment', 'DRP'),
    ('Fitness and Wellness', 'FTW'),
    ('Gifts and Occasions', 'GTO'),
    ('Hobbies and Recreation', 'HBR'),
    ('Pet Expenses', 'PET'),
    ('Retirement', 'RET'),
    ('Subscriptions', 'SUB'),
    ('Work-related Expenses', 'WRK'),
    ('Clothing', 'CLT'),
    ('Electronics', 'ELC'),
    ('Personal Care', 'PRC'),
    ('Internet Services', 'ITS'),
    ('Phone Services', 'PHS'),
    ('Home Maintenance', 'HMT'),
    ('Charitable Contributions', 'CHR'),
    ('Gifts', 'GFT'),
    ('Books and Magazines', 'BKM'),
    ('Professional Services', 'PRS'),
    ('Child Expenses', 'CHE'),
    ('Vehicle Expenses', 'VEH'),
    ('Home Appliances', 'HAP'),
    ('Education Expenses', 'EEX'),
    ('Home Decor', 'HDC'),
    ('Legal Services', 'LGS'),
    ('Sports and Fitness Equipment', 'SFE'),
    ('Health and Wellness', 'HAW'),
    ('Home Services', 'HSV'),
    ('Art and Crafts', 'ARC'),
    ('Coffee and Beverages', 'CNB'),
    ('Streaming Services', 'STS'),
    ('Hobbies', 'HBB'),
    ('Tax Preparation', 'TXP'),
    ('Home Insurance', 'HN$'),
    ('Property Taxes', 'PRT'),
    ('Furniture', 'FUR'),
    ('Bank Fees', 'BKF'),
    ('Office Supplies', 'OFS'),
    ('Health Insurance', 'HI$'),
    ('Home Repairs', 'HRR'),
    ('Internet', 'INT'),
    ('Cable and Satellite TV', 'CST'),
    ('Music and Podcasts', 'MUP'),
    ('Parking', 'PKN'),
    ('Public Transportation', 'PBT'),
    ('Home Security', 'HSE'),
    ('Investment Fees', 'IVF'),
    ('Medical Expenses', 'MEX'),
    ('Car Insurance', 'CI$'),
    ('Home Cleaning', 'HCL'),
    ('Eating Out', 'EOT'),
    ('Car Maintenance', 'CMA'),
    ('School Supplies', 'SSP'),
    ('Gift Cards', 'GCR'),
    ('Home Upgrades', 'HUP'),
    ('Gym Memberships', 'GYM'),
    ('Vacation', 'VAC'),
    ('Magazine Subscriptions', 'MSB'),
    ('Home Loans', 'HLO'),
    ('Grocery Delivery', 'GDL'),
    ('Home Renovations', 'HRN');